# Generated by Django 3.1.1 on 2020-10-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='retweeted',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='retweet',
            field=models.BooleanField(default=False),
        ),
    ]
